name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: [self-hosted, linux, x64]
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Docker login
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "mrusman1" --password-stdin

      - name: Build backend image
        run: docker build -t mrusman1/mern-backend:latest ./server

      - name: Build frontend image
        run: docker build -t mrusman1/mern-frontend:latest ./client

      - name: Push backend image
        run: docker push mrusman1/mern-backend:latest

      - name: Push frontend image
        run: docker push mrusman1/mern-frontend:latest
