name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Docker login
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "mrusman1" --password-stdin

      - name: Build backend image
        run: docker build -t mrusman1/mern-backend:latest -t mrusman1/mern-backend:${{ github.sha }} ./server

      - name: Build frontend image
        run: docker build -t mrusman1/mern-frontend:latest -t mrusman1/mern-frontend:${{ github.sha }} ./client

      - name: Push backend images
        run: docker push mrusman1/mern-backend:latest && docker push mrusman1/mern-backend:${{ github.sha }}

      - name: Push frontend images
        run: docker push mrusman1/mern-frontend:latest && docker push mrusman1/mern-frontend:${{ github.sha }}
